/** Category colors from Blockly_Robotics_IDE_Blueprint.md */
export const CATEGORY_COLORS = {
  project: '#5C81A6',
  board: '#2196F3',
  pin: '#2196F3',
  digital: '#2196F3',
  analog: '#5C68A6',
  pwm: '#FF9800',
  interrupt: '#607D8B',
  timers: '#5CA65C',
  logic: '#5C81A6',
  loops: '#5CA65C',
  math: '#5C68A6',
  variables: '#A65C81',
  strings: '#5BA58C',
  sensors: '#4CAF50',
  actuators: '#FF9800',
  communication: '#00BCD4',
  wireless: '#3F51B5',
  cloudIot: '#673AB7',
  display: '#9C27B0',
  robotics: '#E91E63',
  filesystem: '#795548',
  rtos: '#455A64',
  voice: '#E040FB',
} as const;

export const BLOCKLY_TOOLBOX_CATEGORIES = [
  { kind: 'category', name: 'Project', colour: CATEGORY_COLORS.project, custom: 'STEMVERSE_PROJECT' },
  { kind: 'category', name: 'Pin Config', colour: CATEGORY_COLORS.pin, custom: 'STEMVERSE_PIN' },
  { kind: 'category', name: 'Digital I/O', colour: CATEGORY_COLORS.digital, custom: 'STEMVERSE_DIGITAL' },
  { kind: 'category', name: 'Analog I/O', colour: CATEGORY_COLORS.analog, custom: 'STEMVERSE_ANALOG' },
  { kind: 'category', name: 'PWM', colour: CATEGORY_COLORS.pwm, custom: 'STEMVERSE_PWM' },
  { kind: 'category', name: 'Interrupts', colour: CATEGORY_COLORS.interrupt, custom: 'STEMVERSE_INTERRUPT' },
  { kind: 'category', name: 'Timers', colour: CATEGORY_COLORS.timers, custom: 'STEMVERSE_TIMERS' },
] as const;

export const ROBOTICS_BLOCK_TYPES = [
  'stemverse_program',
  'stemverse_setup',
  'stemverse_loop',
  'stemverse_function_def',
  'stemverse_call_function',
  'stemverse_set_variable',
  'stemverse_constant',
  'stemverse_comment',
  'stemverse_include_library',
  'stemverse_configure_pin',
  'stemverse_digital_write',
  'stemverse_digital_read',
  'stemverse_toggle_pin',
  'stemverse_analog_read',
  'stemverse_analog_write',
  'stemverse_dac_output',
  'stemverse_pwm_setup',
  'stemverse_pwm_write',
  'stemverse_attach_interrupt',
  'stemverse_detach_interrupt',
  'stemverse_delay',
  'stemverse_delay_micros',
  'stemverse_millis',
  'stemverse_micros',
  'stemverse_serial_begin',
] as const;

export type RoboticsBlockType = (typeof ROBOTICS_BLOCK_TYPES)[number];
